name: Trading Bot Automation

# טריגרים
on:
  push:
    branches: [ main, master ]   # ירוץ בכל push למאסטר/מיין
  schedule:
    - cron: "0 * * * *"          # ירוץ כל שעה
  workflow_dispatch:             # אפשר להריץ ידנית מה-Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout הקוד
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. התקנת Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Cache ל-pip
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. התקנת תלותיות
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. הרצת הבוט האמיתי
      - name: Run trading bot
        run: |
          python main.py